### ISSUE TITLE
exit error  on 0.1.22 (23.6.0 upstream)

### ISSUE THREAD

**Issue by hl4gkf** [dappnode/DAppNodePackage-web3signer-prater#102]
**Describe the bug**

**To Reproduce**

when i exit  validator  I got a below error 

0x9350...01b6
Status: Not exited ❌
Message: Error exiting validator could not decode request body: json: cannot unmarshal object into Go struct field SignedVoluntaryExitJson.signature of type stringError posting (POST) voluntary exits to beaconchain.

**Expected behavior**

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

I download  exit json file.. & check.    signature secion was twice generation in json file 

"signature":{"signature":        ........................... }

**Comment by dappnodedev** [comment]
Hey @hl4gkf ! It should be fixed by now. Please, check that this is the case for you after making sure your signer is up-to-date
