### ISSUE TITLE
Test validation user onboarding in network prater

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-web3signer-prater#38]
**Test instructions**

Your role will be to become a new user about to start validating in prater with the web3signer. Having installed web3signer-prater + client test the onboarding process to start validating. 

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

If no errors leave a checkmark

**Testers**

@pablomendezroyo :heavy_check_mark: 
@3alpha
@tropicar
@mgarciate
@Pol-Lanski ✔️

**Comment by Pol-Lanski** [comment]
Blocked by core version 0.2.50 https://github.com/dappnode/DNP_DAPPMANAGER/releases/tag/v0.2.50
In order to test with the latest web3signer version, the CORE needs to be updated.
