### ISSUE TITLE
pid7 error , no attestation with web3signer package latest version

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodePackage-web3signer-prater#40]
**Describe the bug**

Once you install the latest version of prysm-prater(1.0.24) and web3signer(0.1.4 ) the web3signer container does not stop restarting and this error appeared on the logs:

**To Reproduce**

<!--Steps to reproduce the behaviour:
1. Install the new version of both packages

**Expected behaviour**

It should work as it should.

**Screenshots**

![error-web3signer](https://user-images.githubusercontent.com/59098811/170499499-022cd989-de83-48e4-920a-4c23831557fb.png)

**Additional context**

The previous version works with no problem, so there were some changes in the web3signer package and prater that generates this error.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNodePackage-web3signer-prater/issues/41
